<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Validation/*.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../GPCChecker.CompositeBridge/GPCChecker.CompositeBridge.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>
  <ItemGroup Condition="'$(BridgeLibraryDir)' == ''">
    <Reference Include="GPCModel"><HintPath>../../Model/Model/bin/Release/netstandard2.0/GPCModel.dll</HintPath></Reference>
    <Reference Include="GPCModelData"><HintPath>../../Model/ModelData/bin/Release/netstandard2.0/GPCModelData.dll</HintPath></Reference>
    <Reference Include="GPCGeometry"><HintPath>../../Geometry/GPCGeometry/bin/Release/netstandard2.0/GPCGeometry.dll</HintPath></Reference>
    <Reference Include="GPCUtilities"><HintPath>../../Utilities/GPCUtilities/bin/Release/netstandard2.0/GPCUtilities.dll</HintPath></Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(BridgeLibraryDir)' != ''">
    <Reference Include="GPCModel"><HintPath>$(BridgeLibraryDir)/GPCModel.dll</HintPath></Reference>
    <Reference Include="GPCModelData"><HintPath>$(BridgeLibraryDir)/GPCModelData.dll</HintPath></Reference>
    <Reference Include="GPCGeometry"><HintPath>$(BridgeLibraryDir)/GPCGeometry.dll</HintPath></Reference>
    <Reference Include="GPCUtilities"><HintPath>$(BridgeLibraryDir)/GPCUtilities.dll</HintPath></Reference>
  </ItemGroup>
</Project>
