using System.Text.Json.Nodes;
using GPC.Checkers.CompositeBridge.History;
using GPC.Model.Materials;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CompositeBridgeTests;

/// <summary>Frozen results generated by an external OpenSees 3.8.0 executable.
/// Expected values are never generated by Checker. Regenerate with Validation/opensees_reference.py.</summary>
[TestClass, DoNotParallelize]
public class OpenSeesReferenceTests
{
    static JsonObject Reference => JsonNode.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Validation", "opensees-3.8.0.json")))!.AsObject();
    public static IEnumerable<object[]> Cases() => Reference["cases"]!.AsArray().SelectMany((c, i) => c!["stages"]!.AsArray().Select((_, j) => new object[] { i, j }));
    static double D(JsonNode n, string key) => n[key]!.GetValue<double>();
    [DataTestMethod, DynamicData(nameof(Cases), DynamicDataSourceType.Method)]
    public void SectionHistoryMatchesOpenSees(int caseIndex, int stageIndex)
    {
        var c = Reference["cases"]![caseIndex]!;
        int substeps = c["substeps"]?.GetValue<int>() ?? Reference["substeps"]!.GetValue<int>();
        var fibers = c["fibers"]!.AsArray().Select((f, i) => (Id: f!["component"]!.GetValue<string>(), Fiber: new HistoryFiber("f" + i, 0, D(f!, "y"), D(f!, "area")))).ToArray();
        IHistoryMaterialLaw steel = c["plastic"]!.GetValue<bool>() ? new HistoryBilinearSteelLaw(200000, 250, 2000) : new HistoryElasticLaw(200000);
        var concreteMaterial = new Material("Reference tabulation", new StressStrainTable([0, -22.5, -30, -30], [0, -.001, -.002, -.0035]),
            new StressStrainTable([0, 0], [0, .01]), 30000, 30000, .2, 0, 0);
        IHistoryMaterialLaw concrete = c["concrete"]!.GetValue<bool>() ? new HistoryModelEnvelopeLaw(concreteMaterial) : new HistoryElasticLaw(30000);
        bool cast = c["name"]!.GetValue<string>() == "cast_then_shrink";
        var section = new HistorySection(fibers.GroupBy(f => f.Id).Select(g => new HistoryComponent(g.Key, g.Key == "steel" ? steel : concrete,
            g.Select(f => f.Fiber).ToArray(), g.Key == "steel" || !cast)).ToArray());
        var phases = new List<HistoryPhase>();
        double oldN = 0, oldM = 0;
        if (cast) { phases.Add(new() { Name = "Casting reference", DeltaM = 8e7, Substeps = substeps }); oldM = 8e7; }
        double eigen = D(c, "eigen");
        foreach (var row in c["stages"]!.AsArray().Take(stageIndex + 1))
        {
            bool first = phases.Count == (cast ? 1 : 0);
            phases.Add(new() { Name = c["name"]!.GetValue<string>(), DeltaN = D(row!, "n") - oldN, DeltaM = D(row!, "m") - oldM, Substeps = substeps,
                Activate = cast && first ? ["concrete"] : [],
                ImposedStrainIncrements = first && eigen != 0 ? new Dictionary<string, HistoryStrainPlane> { ["concrete"] = new(eigen, 0) } : new Dictionary<string, HistoryStrainPlane>() });
            oldN = D(row!, "n"); oldM = D(row!, "m");
        }
        var actual = BridgeHistoryAnalysis.Calculate(section, phases).Stages.Last();
        var expected = c["stages"]![stageIndex]!;
        var ordered = fibers.Select((_, i) => actual.Fibers.Single(f => f.Fiber.Id == "f" + i)).ToArray();
        double stressError = ordered.Select((f, i) => Math.Abs(f.Stress - expected["stresses"]![i]!.GetValue<double>())).Max();
        double strainError = ordered.Select((f, i) => Math.Abs(f.TotalStrain - expected["strains"]![i]!.GetValue<double>())).Max();
        Console.WriteLine($"{c["name"]}[{stageIndex}]: maxDeltaStress={stressError:R} MPa; maxDeltaStrain={strainError:R}; deltaE0={Math.Abs(D(expected, "axial") - actual.TotalPlane.AxialStrain):R}; deltaK={Math.Abs(D(expected, "curvature") - actual.TotalPlane.Curvature):R}");
        // Reversal paths cross yield corners. A 20 -> 200 -> 2000 -> 20000
        // substep study establishes the finite-step comparison floor (see Validation/README).
        // 0.02 microstrain and E*0.02 microstrain = 0.004 MPa are absolute bounds,
        // NOT a percent of large plastic strains. Actual maxima are recorded in the TRX.
        bool reversal = caseIndex == 2 && stageIndex >= 4 || caseIndex == 3 && stageIndex >= 4;
        double strainTolerance = reversal ? 2e-8 : 2e-10;
        void Near(double a, double b, double abs, string label) => Assert.AreEqual(a, b, abs + 2e-7 * Math.Abs(a), c["name"] + $"[{stageIndex}] " + label);
        Near(D(expected, "axial"), actual.TotalPlane.AxialStrain, strainTolerance, "epsilon0");
        Near(D(expected, "curvature"), actual.TotalPlane.Curvature, 2e-12, "kappa");
        for (int i = 0; i < fibers.Length; i++)
        {
            var f = actual.Fibers.Single(f => f.Fiber.Id == "f" + i);
            Near(expected["stresses"]![i]!.GetValue<double>(), f.Stress, reversal ? 200000 * strainTolerance : 2e-5, "stress " + i);
            // InitStrainMaterial recorder exposes the wrapper strain, not underlying material strain.
            Near(expected["strains"]![i]!.GetValue<double>(), f.TotalStrain, strainTolerance, "total strain " + i);
        }
    }
}
