param([string]$Source = (Join-Path $PSScriptRoot "..\..\..\SezioneComposta\DT-NTC2008\Form1.cs"), [string]$Output = (Join-Path $PSScriptRoot "VivianiOriginal.cs"))
# Mechanical extraction of the calculation of SezioneComposta (Form1.Button1_Click) into a class without UI:
# TextBox reads -> input fields, TextBox writes -> output fields (full precision), ForeColor -> string fields, CheckBox -> bool.
$src = $Source
$lines = Get-Content $src
$start = ($lines | Select-String -Pattern 'private void Button1_Click' | Select-Object -First 1).LineNumber
$end = ($lines | Select-String -Pattern 'private void Form1_Load' | Select-Object -First 1).LineNumber
# body: from the line after "{" of Button1_Click to the closing "}" before Form1_Load
$body = $lines[($start + 1)..($end - 5)]
$fields = $lines | Select-String -Pattern '^\s*private (double|int) \w+;' | ForEach-Object { $_.Line.Trim() }
$inputs = New-Object System.Collections.Generic.SortedSet[string]
$outputs = New-Object System.Collections.Generic.SortedSet[string]
$colors = New-Object System.Collections.Generic.SortedSet[string]
$out = foreach ($l in $body) {
    $t = $l
    foreach ($m in [regex]::Matches($t, 'Conversion\.Val\(this\.(TextBox\d+)\.Text\)')) { [void]$inputs.Add($m.Groups[1].Value) }
    $t = [regex]::Replace($t, 'Conversion\.Val\(this\.(TextBox\d+)\.Text\)', 'this.in$1')
    $t = $t.Replace('this.CheckBox1.Checked', 'this.inCheckBox1')
    $m = [regex]::Match($t, 'this\.(TextBox\d+)\.ForeColor = Color\.(\w+);')
    if ($m.Success) { [void]$colors.Add($m.Groups[1].Value); $t = $t.Replace($m.Value, "this.color$($m.Groups[1].Value) = `"$($m.Groups[2].Value)`";") }
    $m = [regex]::Match($t, 'this\.(TextBox\d+)\.Text = Strings\.FormatNumber\((.+), (\d+), TriState\.UseDefault, TriState\.UseDefault, TriState\.UseDefault\);')
    if ($m.Success) { [void]$outputs.Add($m.Groups[1].Value); $t = $t.Replace($m.Value, "this.out$($m.Groups[1].Value) = $($m.Groups[2].Value);") }
    if ($t -match 'this\.TextBox\d+\.|Strings\.|Conversion\.|this\.CheckBox') { throw "Riga non convertita: $l" }
    $t
}
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// Mechanical extraction of SezioneComposta (DT-NTC2008, Form1.Button1_Click, decompiled) by extract-viviani.ps1: the calculation is')
[void]$sb.AppendLine('// verbatim; the reads of the text boxes are input fields, the writes are output fields at full precision (the program rounds them only for')
[void]$sb.AppendLine('// the display), the colours are strings and the check box is a bool. Reference of the clean rewrite GPC.Checkers.CompositeBridge.Viviani.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine('#pragma warning disable')
[void]$sb.AppendLine('namespace CompositeBridgeTests.Viviani')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    internal sealed class VivianiOriginal')
[void]$sb.AppendLine('    {')
foreach ($f in $fields) { [void]$sb.AppendLine("        public $($f.Substring(8))") }
foreach ($i in $inputs) { [void]$sb.AppendLine("        public double in$i;") }
[void]$sb.AppendLine('        public bool inCheckBox1;')
foreach ($o in $outputs) { [void]$sb.AppendLine("        public double out$o;") }
foreach ($c in $colors) { [void]$sb.AppendLine("        public string color$c = `"`";") }
[void]$sb.AppendLine('')
[void]$sb.AppendLine('        public void Button1_Click()')
[void]$sb.AppendLine('        {')
foreach ($l in $out) { [void]$sb.AppendLine('    ' + $l.TrimEnd()) }
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')
[IO.File]::WriteAllText($Output, $sb.ToString().Replace("`r`n", "`n"), (New-Object Text.UTF8Encoding($false)))
"input: " + ($inputs -join ', ')
"output: " + ($outputs -join ', ')
"colori: " + ($colors -join ', ')
"righe corpo: $($out.Count)"
