// <auto-generated>
// Mechanical extraction of SezioneComposta (DT-NTC2008, Form1.Button1_Click, decompiled) by extract-viviani.ps1: the calculation is
// verbatim; the reads of the text boxes are input fields, the writes are output fields at full precision (the program rounds them only for
// the display), the colours are strings and the check box is a bool. Reference of the clean rewrite GPC.Checkers.CompositeBridge.Viviani.
// </auto-generated>
#pragma warning disable
namespace CompositeBridgeTests.Viviani
{
    internal sealed class VivianiOriginal
    {
        public double tpi;
        public double bpi;
        public double haw;
        public double taw;
        public double tps;
        public double bps;
        public double hs;
        public double bs;
        public double ninf;
        public double n0;
        public double rs;
        public double afs;
        public double sninf;
        public double snninf;
        public double snn0;
        public double stinf;
        public double stninf;
        public double stn0;
        public double sminf;
        public double smninf;
        public double smn0;
        public double y1;
        public double y2;
        public double y3;
        public double y4;
        public double y5;
        public double y6;
        public double ainf;
        public double yginf;
        public double jx0inf;
        public double ad2inf;
        public double jxinf;
        public double w1inf;
        public double w2inf;
        public double w3inf;
        public double w4inf;
        public double w5inf;
        public double w6inf;
        public double aninf;
        public double ygninf;
        public double jx0ninf;
        public double ad2ninf;
        public double jxninf;
        public double w1ninf;
        public double w2ninf;
        public double w3ninf;
        public double w4ninf;
        public double w5ninf;
        public double w6ninf;
        public double aninf1;
        public double ygninf1;
        public double jx0ninf1;
        public double ad2ninf1;
        public double jxninf1;
        public double w1ninf1;
        public double w2ninf1;
        public double w3ninf1;
        public double w4ninf1;
        public double w5ninf1;
        public double w6ninf1;
        public double an0;
        public double ygn0;
        public double jx0n0;
        public double ad2n0;
        public double jxn0;
        public double w1n0;
        public double w2n0;
        public double w3n0;
        public double w4n0;
        public double w5n0;
        public double w6n0;
        public double an01;
        public double ygn01;
        public double jx0n01;
        public double ad2n01;
        public double jxn01;
        public double w1n01;
        public double w2n01;
        public double w3n01;
        public double w4n01;
        public double w5n01;
        public double w6n01;
        public double anr;
        public double ygnr;
        public double jx0nr;
        public double ad2nr;
        public double jxnr;
        public double w1nr;
        public double w2nr;
        public double w3nr;
        public double w4nr;
        public double w5nr;
        public double w6nr;
        public double srninf;
        public double srninf1;
        public double srn0;
        public double srn01;
        public double srnr;
        public double par1;
        public double pass;
        public double htninf;
        public double htninf1;
        public double htn0;
        public double htn01;
        public double htnr;
        public double fcd;
        public double fydps;
        public double fyda;
        public double fyda1;
        public double fydpi;
        public double fydar;
        public double ctr;
        public double cte;
        public double ctp;
        public int cle;
        public int clp;
        public int niter;
        public int iter;
        public int iterp;
        public double gammag1;
        public double gammag2;
        public double gammaq;
        public double coeff1;
        public double coeffg1;
        public double coeffg2;
        public double coeffq;
        public double lamp;
        public double ro;
        public double beff;
        public double be1;
        public double be2;
        public double haw1;
        public double ypl;
        public double yel;
        public double mtot;
        public double ttot;
        public double u1;
        public double nr;
        public double u2;
        public double u3;
        public double ua;
        public double ue;
        public double mpl;
        public double sig1;
        public double sig2;
        public double sig3;
        public double sig4;
        public double sig5;
        public double sig6;
        public double tau4;
        public double tau5;
        public double sigid3;
        public double sigid4;
        public double sigid5;
        public double sigid6;
        public double taub;
        public double HP;
        public double va;
        public double hp1;
        public double TW1;
        public double passo;
        public double sigma1;
        public double sigma2;
        public double tau;
        public double h1;
        public double h2;
        public double nibeta;
        public double sigma3;
        public double sigma4;
        public double sigma5;
        public double fd;
        public double fy;
        public double psi;
        public double affa;
        public double scr0;
        public double ktau;
        public double ksig;
        public double k1;
        public double k3;
        public double k2;
        public double tacr;
        public double sicr;
        public double scrid;
        public double scred;
        public double inTextBox1;
        public double inTextBox11;
        public double inTextBox16;
        public double inTextBox17;
        public double inTextBox18;
        public double inTextBox2;
        public double inTextBox24;
        public double inTextBox27;
        public double inTextBox28;
        public double inTextBox29;
        public double inTextBox3;
        public double inTextBox30;
        public double inTextBox31;
        public double inTextBox32;
        public double inTextBox33;
        public double inTextBox34;
        public double inTextBox4;
        public double inTextBox45;
        public double inTextBox46;
        public double inTextBox47;
        public double inTextBox48;
        public double inTextBox5;
        public double inTextBox54;
        public double inTextBox55;
        public double inTextBox56;
        public double inTextBox6;
        public double inTextBox62;
        public double inTextBox7;
        public double inTextBox8;
        public double inTextBox9;
        public bool inCheckBox1;
        public double outTextBox1;
        public double outTextBox10;
        public double outTextBox11;
        public double outTextBox12;
        public double outTextBox13;
        public double outTextBox14;
        public double outTextBox15;
        public double outTextBox16;
        public double outTextBox17;
        public double outTextBox18;
        public double outTextBox19;
        public double outTextBox2;
        public double outTextBox20;
        public double outTextBox21;
        public double outTextBox22;
        public double outTextBox23;
        public double outTextBox24;
        public double outTextBox25;
        public double outTextBox26;
        public double outTextBox27;
        public double outTextBox28;
        public double outTextBox29;
        public double outTextBox3;
        public double outTextBox30;
        public double outTextBox31;
        public double outTextBox32;
        public double outTextBox33;
        public double outTextBox34;
        public double outTextBox35;
        public double outTextBox36;
        public double outTextBox37;
        public double outTextBox38;
        public double outTextBox39;
        public double outTextBox4;
        public double outTextBox40;
        public double outTextBox41;
        public double outTextBox42;
        public double outTextBox43;
        public double outTextBox44;
        public double outTextBox45;
        public double outTextBox46;
        public double outTextBox47;
        public double outTextBox48;
        public double outTextBox49;
        public double outTextBox5;
        public double outTextBox50;
        public double outTextBox51;
        public double outTextBox52;
        public double outTextBox53;
        public double outTextBox57;
        public double outTextBox58;
        public double outTextBox59;
        public double outTextBox6;
        public double outTextBox60;
        public double outTextBox61;
        public double outTextBox62;
        public double outTextBox7;
        public double outTextBox8;
        public double outTextBox9;
        public string colorTextBox1 = "";
        public string colorTextBox13 = "";
        public string colorTextBox24 = "";
        public string colorTextBox47 = "";
        public string colorTextBox51 = "";
        public string colorTextBox53 = "";

        public void Button1_Click()
        {
    			this.colorTextBox13 = "Black";
    			this.colorTextBox51 = "Black";
    			this.colorTextBox53 = "Black";
    			this.colorTextBox47 = "Green";
    			this.colorTextBox24 = "Black";
    			this.colorTextBox1 = "Black";
    			this.yel = 0.0;
    			this.ypl = 0.0;
    			this.clp = 0;
    			this.cle = 0;
    			this.cte = 0.0;
    			this.ctp = 0.0;
    			this.ctr = 0.0;
    			this.mtot = 0.0;
    			this.ttot = 0.0;
    			this.nibeta = 0.0;
    			this.mpl = 0.0;
    			this.hs = this.inTextBox2;
    			this.bs = this.inTextBox9;
    			this.rs = this.inTextBox18;
    			this.afs = this.inTextBox24;
    			this.tps = this.inTextBox8;
    			this.bps = this.inTextBox7;
    			this.haw = this.inTextBox4;
    			this.taw = this.inTextBox1;
    			this.tpi = this.inTextBox3;
    			this.bpi = this.inTextBox17;
    			this.n0 = this.inTextBox5;
    			this.ninf = this.inTextBox6;
    			this.fydar = this.inTextBox16;
    			this.sninf = this.inTextBox32;
    			this.snninf = this.inTextBox27;
    			this.snn0 = this.inTextBox11;
    			this.stinf = this.inTextBox33;
    			this.stninf = this.inTextBox28;
    			this.stn0 = this.inTextBox30;
    			this.sminf = this.inTextBox34;
    			this.smninf = this.inTextBox29;
    			this.smn0 = this.inTextBox31;
    			this.fcd = this.inTextBox45;
    			this.fydps = this.inTextBox46;
    			this.fyda1 = this.inTextBox47;
    			this.fydpi = this.inTextBox48;
    			this.niter = checked((int)Math.Round(this.inTextBox62));
    			this.gammag1 = this.inTextBox54;
    			this.gammag2 = this.inTextBox55;
    			this.gammaq = this.inTextBox56;
    			this.coeffg1 = 1.0;
    			this.coeffg2 = 1.0;
    			this.coeffq = 1.0;
    			if (this.inCheckBox1)
    			{
    				this.coeffg1 = this.gammag1;
    				this.coeffg2 = this.gammag2;
    				this.coeffq = this.gammaq;
    			}
    			this.y1 = this.tpi + this.haw + this.tps + this.hs;
    			this.y2 = this.y1 - this.rs;
    			this.y3 = this.y1 - this.hs;
    			this.y4 = this.y3 - this.tps;
    			this.y5 = this.y4 - this.haw;
    			this.y6 = 0.0;
    			this.iter = 0;
    			this.iterp = 0;
    			this.ctr = this.haw / this.taw;
    			this.be1 = this.haw / 2.0;
    			this.be2 = this.haw / 2.0;
    			this.fyda = this.fyda1;
    			for (;;)
    			{
    				this.ainf = this.bps * this.tps + this.be1 * this.taw + this.be2 * this.taw + this.tpi * this.bpi;
    				this.yginf = (this.bps * this.tps * (this.tpi + this.haw + this.tps / 2.0) + this.be1 * this.taw * (this.tpi + this.haw - this.be1 / 2.0) + this.be2 * this.taw * (this.tpi + this.be2 / 2.0) + this.tpi * this.bpi * this.tpi / 2.0) / this.ainf;
    				this.jx0inf = Math.Pow(this.tpi, 3.0) * this.bpi / 12.0 + Math.Pow(this.be2, 3.0) * this.taw / 12.0 + Math.Pow(this.be1, 3.0) * this.taw / 12.0 + Math.Pow(this.tps, 3.0) * this.bps / 12.0;
    				this.ad2inf = this.bps * this.tps * Math.Pow(this.tpi + this.haw + this.tps / 2.0 - this.yginf, 2.0) + this.be1 * this.taw * Math.Pow(this.tpi + this.haw - this.be1 / 2.0 - this.yginf, 2.0) + this.be2 * this.taw * Math.Pow(this.tpi + this.be2 / 2.0 - this.yginf, 2.0) + this.bpi * this.tpi * Math.Pow(this.tpi / 2.0 - this.yginf, 2.0);
    				this.jxinf = this.jx0inf + this.ad2inf;
    				this.w1inf = 0.0;
    				this.w2inf = 0.0;
    				this.w3inf = this.jxinf / (this.yginf - this.y3);
    				this.w4inf = this.jxinf / (this.yginf - this.y4);
    				this.w5inf = this.jxinf / (this.yginf - this.y5);
    				this.w6inf = this.jxinf / (this.yginf - this.y6);
    				this.aninf1 = this.ainf + this.bs * this.hs / this.ninf + this.afs;
    				this.ygninf1 = (this.ainf * this.yginf + this.afs * this.y2 + this.bs * this.hs / this.ninf * (this.y1 - this.hs / 2.0)) / this.aninf1;
    				this.jx0ninf1 = this.jxinf + Math.Pow(this.hs, 3.0) * this.bs / (12.0 * this.ninf);
    				this.ad2ninf1 = this.ainf * Math.Pow(this.yginf - this.ygninf1, 2.0) + this.bs * this.hs / this.ninf * Math.Pow(this.y1 - this.hs / 2.0 - this.ygninf1, 2.0) + this.afs * Math.Pow(this.y2 - this.ygninf1, 2.0);
    				this.jxninf1 = this.jx0ninf1 + this.ad2ninf1;
    				this.srninf1 = this.bs * this.hs / this.ninf * (this.y1 - this.hs / 2.0 - this.ygninf1) + this.afs * (this.y2 - this.ygninf1);
    				this.htninf1 = this.jxninf1 / this.srninf1;
    				this.w1ninf1 = this.jxninf1 / (this.ygninf1 - this.y1) * this.ninf;
    				this.w2ninf1 = this.jxninf1 / (this.ygninf1 - this.y2);
    				this.w3ninf1 = this.jxninf1 / (this.ygninf1 - this.y3);
    				this.w4ninf1 = this.jxninf1 / (this.ygninf1 - this.y4);
    				this.w5ninf1 = this.jxninf1 / (this.ygninf1 - this.y5);
    				this.w6ninf1 = this.jxninf1 / (this.ygninf1 - this.y6);
    				this.an01 = this.ainf + this.bs * this.hs / this.n0 + this.afs;
    				this.ygn01 = (this.ainf * this.yginf + this.afs * this.y2 + this.bs * this.hs / this.n0 * (this.y1 - this.hs / 2.0)) / this.an01;
    				this.jx0n01 = this.jxinf + Math.Pow(this.hs, 3.0) * this.bs / (12.0 * this.n0);
    				this.ad2n01 = this.ainf * Math.Pow(this.yginf - this.ygn01, 2.0) + this.bs * this.hs / this.n0 * Math.Pow(this.y1 - this.hs / 2.0 - this.ygn01, 2.0) + this.afs * Math.Pow(this.y2 - this.ygn01, 2.0);
    				this.jxn01 = this.jx0n01 + this.ad2n01;
    				this.srn01 = this.bs * this.hs / this.n0 * (this.y1 - this.hs / 2.0 - this.ygn01) + this.afs * (this.y2 - this.ygn01);
    				this.htn01 = this.jxn01 / this.srn01;
    				this.w1n01 = this.jxn01 / (this.ygn01 - this.y1) * this.n0;
    				this.w2n01 = this.jxn01 / (this.ygn01 - this.y2);
    				this.w3n01 = this.jxn01 / (this.ygn01 - this.y3);
    				this.w4n01 = this.jxn01 / (this.ygn01 - this.y4);
    				this.w5n01 = this.jxn01 / (this.ygn01 - this.y5);
    				this.w6n01 = this.jxn01 / (this.ygn01 - this.y6);
    				this.anr = this.ainf + this.afs;
    				this.ygnr = (this.ainf * this.yginf + this.afs * this.y2) / this.anr;
    				this.jx0nr = this.jxinf;
    				this.ad2nr = this.ainf * Math.Pow(this.yginf - this.ygnr, 2.0) + this.afs * Math.Pow(this.y2 - this.ygnr, 2.0);
    				this.jxnr = this.jx0nr + this.ad2nr;
    				this.srnr = this.afs * (this.y2 - this.ygnr);
    				this.htnr = this.jxnr / this.srnr;
    				this.w1nr = 0.0;
    				this.w2nr = this.jxnr / (this.ygnr - this.y2);
    				this.w3nr = this.jxnr / (this.ygnr - this.y3);
    				this.w4nr = this.jxnr / (this.ygnr - this.y4);
    				this.w5nr = this.jxnr / (this.ygnr - this.y5);
    				this.w6nr = this.jxnr / (this.ygnr - this.y6);
    				this.jxninf = this.jxninf1;
    				this.aninf = this.aninf1;
    				this.ygninf = this.ygninf1;
    				this.w1ninf = this.w1ninf1;
    				this.w2ninf = this.w2ninf1;
    				this.w3ninf = this.w3ninf1;
    				this.w4ninf = this.w4ninf1;
    				this.w5ninf = this.w5ninf1;
    				this.w6ninf = this.w6ninf1;
    				this.htninf = this.htninf1;
    				this.jxn0 = this.jxn01;
    				this.an0 = this.an01;
    				this.ygn0 = this.ygn01;
    				this.w1n0 = this.w1n01;
    				this.w2n0 = this.w2n01;
    				this.w3n0 = this.w3n01;
    				this.w4n0 = this.w4n01;
    				this.w5n0 = this.w5n01;
    				this.w6n0 = this.w6n01;
    				this.htn0 = this.htn01;
    				this.par1 = this.snninf * this.coeffg2 / (this.aninf * this.ninf) + this.snn0 * this.coeffq / (this.an0 * this.n0) + this.coeffg2 * this.smninf * 100.0 / this.w1ninf + this.coeffq * this.smn0 * 100.0 / this.w1n0;
    				if (this.par1 > 1E-05 | this.hs <= 0.0)
    				{
    					this.jxninf = this.jxnr;
    					this.aninf = this.anr;
    					this.ygninf = this.ygnr;
    					this.w1ninf = this.w1nr;
    					this.w2ninf = this.w2nr;
    					this.w3ninf = this.w3nr;
    					this.w4ninf = this.w4nr;
    					this.w5ninf = this.w5nr;
    					this.w6ninf = this.w6nr;
    					this.htninf = this.htnr;
    					this.jxn0 = this.jxnr;
    					this.an0 = this.anr;
    					this.ygn0 = this.ygnr;
    					this.w1n0 = this.w1nr;
    					this.w2n0 = this.w2nr;
    					this.w3n0 = this.w3nr;
    					this.w4n0 = this.w4nr;
    					this.w5n0 = this.w5nr;
    					this.w6n0 = this.w6nr;
    					this.htn0 = this.htnr;
    				}
    				if (this.par1 < 1E-05 & this.hs > 0.0)
    				{
    					this.sig1 = (this.coeffg2 * this.snninf / (this.aninf * this.ninf) + this.coeffq * this.snn0 / (this.an0 * this.n0) + this.coeffg2 * this.smninf * 100.0 / this.w1ninf + this.coeffq * this.smn0 * 100.0 / this.w1n0) * 10.0;
    				}
    				else
    				{
    					this.sig1 = 0.0;
    				}
    				if (this.hs > 0.0)
    				{
    					this.sig2 = (this.coeffg2 * this.snninf / this.aninf + this.coeffq * this.snn0 / this.an0 + this.coeffg2 * this.smninf * 100.0 / this.w2ninf + this.coeffq * this.smn0 * 100.0 / this.w2n0) * 10.0;
    				}
    				else
    				{
    					this.sig2 = 0.0;
    				}
    				this.sig3 = (this.coeffg1 * this.sninf / this.ainf + this.coeffg2 * this.snninf / this.aninf + this.coeffq * this.snn0 / this.an0 + this.coeffg1 * this.sminf * 100.0 / this.w3inf + this.coeffg2 * this.smninf * 100.0 / this.w3ninf + this.coeffq * this.smn0 * 100.0 / this.w3n0) * 10.0;
    				this.sig4 = (this.coeffg1 * this.sninf / this.ainf + this.coeffg2 * this.snninf / this.aninf + this.coeffq * this.snn0 / this.an0 + this.coeffg1 * this.sminf * 100.0 / this.w4inf + this.coeffg2 * this.smninf * 100.0 / this.w4ninf + this.coeffq * this.smn0 * 100.0 / this.w4n0) * 10.0;
    				this.sig5 = (this.coeffg1 * this.sninf / this.ainf + this.coeffg2 * this.snninf / this.aninf + this.coeffq * this.snn0 / this.an0 + this.coeffg1 * this.sminf * 100.0 / this.w5inf + this.coeffg2 * this.smninf * 100.0 / this.w5ninf + this.coeffq * this.smn0 * 100.0 / this.w5n0) * 10.0;
    				this.sig6 = (this.coeffg1 * this.sninf / this.ainf + this.coeffg2 * this.snninf / this.aninf + this.coeffq * this.snn0 / this.an0 + this.coeffg1 * this.sminf * 100.0 / this.w6inf + this.coeffg2 * this.smninf * 100.0 / this.w6ninf + this.coeffq * this.smn0 * 100.0 / this.w6n0) * 10.0;
    				this.tau4 = Math.Abs(this.coeffg1 * this.stinf + this.coeffg2 * this.stninf + this.coeffq * this.stn0) * 10.0 / ((this.be1 + this.be2) * this.taw);
    				this.tau5 = this.tau4;
    				this.sigid3 = Math.Abs(this.sig3);
    				this.sigid4 = Math.Sqrt(Math.Pow(this.sig4, 2.0) + 3.0 * Math.Pow(this.tau4, 2.0));
    				this.sigid6 = Math.Abs(this.sig6);
    				this.sigid5 = Math.Sqrt(Math.Pow(this.sig5, 2.0) + 3.0 * Math.Pow(this.tau5, 2.0));
    				this.taub = Math.Abs(this.coeffg2 * this.stninf / this.htninf + this.coeffq * this.stn0 / this.htn0);
    				if (this.niter == 0)
    				{
    					break;
    				}
    				if (this.cle == 4 & this.iter >= this.niter)
    				{
    					break;
    				}
    				checked
    				{
    					this.iter++;
    				}
    				if (this.sig4 < 0.0 & this.sig5 < 0.0)
    				{
    					if (this.sig4 < this.sig5)
    					{
    						this.psi = this.sig5 / this.sig4;
    						this.cte = 42.0 * Math.Sqrt(235.0 / this.fyda) / (0.67 + 0.33 * this.psi);
    						if (this.cte >= this.ctr)
    						{
    							goto Block_9;
    						}
    						this.cle = 4;
    						this.ksig = 8.2 / (1.05 + this.psi);
    						this.lamp = this.haw / (28.4 * this.taw * Math.Sqrt(235.0 / this.fyda) * Math.Sqrt(this.ksig));
    						this.ro = 1.0;
    						if (this.lamp > 0.673)
    						{
    							this.ro = (this.lamp - 0.055 * (3.0 + this.psi)) / Math.Pow(this.lamp, 2.0);
    						}
    						if (this.ro > 1.0)
    						{
    							this.ro = 1.0;
    						}
    						this.beff = this.ro * this.haw;
    						this.be1 = 2.0 / (5.0 - this.psi) * this.beff;
    						this.be2 = this.beff - this.be1;
    					}
    					else
    					{
    						this.psi = this.sig4 / this.sig5;
    						this.cte = 42.0 * Math.Sqrt(235.0 / this.fyda) / (0.67 + 0.33 * this.psi);
    						if (this.cte >= this.ctr)
    						{
    							goto Block_12;
    						}
    						this.cle = 4;
    						this.ksig = 8.2 / (1.05 + this.psi);
    						this.lamp = this.haw / (28.4 * this.taw * Math.Sqrt(235.0 / this.fyda) * Math.Sqrt(this.ksig));
    						this.ro = 1.0;
    						if (this.lamp > 0.673)
    						{
    							this.ro = (this.lamp - 0.055 * (3.0 + this.psi)) / Math.Pow(this.lamp, 2.0);
    						}
    						if (this.ro > 1.0)
    						{
    							this.ro = 1.0;
    						}
    						this.beff = this.ro * this.haw;
    						this.be2 = 2.0 / (5.0 - this.psi) * this.beff;
    						this.be1 = this.beff - this.be2;
    					}
    				}
    				else
    				{
    					if (this.sig4 > 0.0 & this.sig5 > 0.0)
    					{
    						goto Block_15;
    					}
    					if (this.sig4 < 0.0)
    					{
    						this.psi = this.sig5 / this.sig4;
    						this.yel = this.sig5 * this.haw / (this.sig5 - this.sig4) + this.tpi;
    						if (this.psi > -1.0)
    						{
    							this.cte = 42.0 * Math.Sqrt(235.0 / this.fyda) / (0.67 + 0.33 * this.psi);
    						}
    						else
    						{
    							this.cte = 62.0 * Math.Sqrt(235.0 / this.fyda) * (1.0 - this.psi) * Math.Sqrt(-1.0 * this.psi);
    						}
    						if (this.cte >= this.ctr)
    						{
    							goto Block_18;
    						}
    						this.cle = 4;
    						this.colorTextBox51 = "Blue";
    						this.ksig = 0.0;
    						if (this.psi < 0.0 & this.psi > -1.0)
    						{
    							this.ksig = 7.81 - 6.29 * this.psi + 9.78 * this.psi * this.psi;
    						}
    						if (this.psi <= -1.0 & this.psi > -3.0)
    						{
    							this.ksig = 5.98 * Math.Pow(1.0 - this.psi, 2.0);
    						}
    						if (this.psi <= -3.0)
    						{
    							this.ksig = 95.68;
    						}
    						this.lamp = this.haw / (28.4 * this.taw * Math.Sqrt(235.0 / this.fyda) * Math.Sqrt(this.ksig));
    						this.ro = 1.0;
    						if (this.lamp > 0.673)
    						{
    							this.ro = (this.lamp - 0.055 * (3.0 + this.psi)) / Math.Pow(this.lamp, 2.0);
    						}
    						if (this.ro > 1.0)
    						{
    							this.ro = 1.0;
    						}
    						this.beff = this.ro * this.haw / (1.0 - this.psi);
    						this.be1 = 0.4 * this.beff;
    						this.be2 = 0.6 * this.beff - this.psi / (1.0 - this.psi) * this.haw;
    					}
    					else
    					{
    						if (this.sig5 >= 0.0)
    						{
    							break;
    						}
    						this.psi = this.sig4 / this.sig5;
    						this.yel = this.sig5 * this.haw / (this.sig5 - this.sig4) + this.tpi;
    						if (this.psi > -1.0)
    						{
    							this.cte = 42.0 * Math.Sqrt(235.0 / this.fyda) / (0.67 + 0.33 * this.psi);
    						}
    						else
    						{
    							this.cte = 62.0 * Math.Sqrt(235.0 / this.fyda) * (1.0 - this.psi) * Math.Sqrt(-1.0 * this.psi);
    						}
    						if (this.cte > this.ctr)
    						{
    							goto Block_26;
    						}
    						this.cle = 4;
    						this.colorTextBox51 = "Aquamarine";
    						this.ksig = 0.0;
    						if (this.psi < 0.0 & this.psi > -1.0)
    						{
    							this.ksig = 7.81 - 6.29 * this.psi + 9.78 * this.psi * this.psi;
    						}
    						if (this.psi <= -1.0 & this.psi > -3.0)
    						{
    							this.ksig = 5.98 * Math.Pow(1.0 - this.psi, 2.0);
    						}
    						if (this.psi <= -3.0)
    						{
    							this.ksig = 95.68;
    						}
    						this.lamp = this.haw / (28.4 * this.taw * Math.Sqrt(235.0 / (this.fyda)) * Math.Sqrt(this.ksig));
    						this.ro = 1.0;
    						if (this.lamp > 0.673)
    						{
    							this.ro = (this.lamp - 0.055 * (3.0 + this.psi)) / Math.Pow(this.lamp, 2.0);
    						}
    						if (this.ro > 1.0)
    						{
    							this.ro = 1.0;
    						}
    						this.beff = this.ro * this.haw / (1.0 - this.psi);
    						this.be2 = 0.4 * this.beff;
    						this.be1 = 0.6 * this.beff - this.psi / (1.0 - this.psi) * this.haw;
    					}
    				}
    			}
    			goto IL_2041;
    			Block_9:
    			this.cle = 3;
    			this.colorTextBox51 = "Green";
    			goto IL_2041;
    			Block_12:
    			this.cle = 3;
    			this.colorTextBox51 = "Green";
    			goto IL_2041;
    			Block_15:
    			this.cle = 3;
    			this.colorTextBox51 = "Green";
    			goto IL_2041;
    			Block_18:
    			this.cle = 3;
    			this.colorTextBox51 = "Green";
    			goto IL_2041;
    			Block_26:
    			this.cle = 3;
    			this.colorTextBox51 = "Green";
    			IL_2041:
    			this.mtot = this.gammag1 * this.sminf + this.gammag2 * this.smninf + this.gammaq * this.smn0;
    			this.ttot = this.gammag1 * this.stinf + this.gammag2 * this.stninf + this.gammaq * this.stn0;
    			this.u1 = this.haw * this.taw * this.fyda / Math.Sqrt(3.0) / 10.0;
    			if (this.ttot > this.u1)
    			{
    				this.taw = 0.0;
    				this.mpl = 0.0;
    				this.colorTextBox1 = "Red";
    				goto IL_38C4;
    			}
    			this.ue = Math.Sqrt(235.0 / this.fyda);
    			IL_212E:
    			if (this.mtot >= 0.0)
    			{
    				this.nr = this.afs * this.fydar + this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi;
    				if (this.bs * this.rs * this.fcd > this.nr)
    				{
    					this.clp = 1;
    					this.ctp = 1000.0;
    					this.u1 = this.nr / (this.bs * this.fcd);
    					this.mpl = this.bs * this.u1 * this.fcd * this.u1 / 2.0;
    					this.mpl += this.afs * this.fydar * (this.rs - this.u1);
    					this.mpl += this.bps * this.tps * this.fydps * (this.hs + this.tps / 2.0 - this.u1);
    					this.mpl += this.haw * this.taw * this.fyda * (this.hs + this.tps + this.haw / 2.0 - this.u1);
    					this.mpl += this.tpi * this.bpi * this.fydpi * (this.hs + this.tps + this.haw + this.tpi / 2.0 - this.u1);
    					this.mpl /= 1000.0;
    					this.ypl = this.tpi + this.haw + this.tps + this.hs - this.u1;
    				}
    				else
    				{
    					this.nr = this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi;
    					if (this.bs * this.rs * this.fcd + this.afs * this.fydar > this.nr)
    					{
    						this.clp = 1;
    						this.ctp = 1000.0;
    						this.u1 = this.rs;
    						this.mpl = this.bs * this.u1 * this.fcd * this.u1 / 2.0;
    						this.mpl += this.bps * this.tps * this.fydps * (this.hs + this.tps / 2.0 - this.u1);
    						this.mpl += this.haw * this.taw * this.fyda * (this.hs + this.tps + this.haw / 2.0 - this.u1);
    						this.mpl += this.tpi * this.bpi * this.fydpi * (this.hs + this.tps + this.haw + this.tpi / 2.0 - this.u1);
    						this.mpl /= 1000.0;
    						this.ypl = this.tpi + this.haw + this.tps + this.hs - this.u1;
    					}
    					else
    					{
    						this.nr = this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi;
    						if (this.bs * this.hs * this.fcd + this.afs * this.fydar > this.nr)
    						{
    							this.clp = 1;
    							this.ctp = 1000.0;
    							this.u1 = (this.nr - this.afs * this.fydar) / (this.bs * this.fcd);
    							this.mpl = this.bs * this.u1 * this.fcd * this.u1 / 2.0;
    							this.mpl += this.afs * this.fydar * (this.u1 - this.rs);
    							this.mpl += this.bps * this.tps * this.fydps * (this.hs + this.tps / 2.0 - this.u1);
    							this.mpl += this.haw * this.taw * this.fyda * (this.hs + this.tps + this.haw / 2.0 - this.u1);
    							this.mpl += this.tpi * this.bpi * this.fydpi * (this.hs + this.tps + this.haw + this.tpi / 2.0 - this.u1);
    							this.mpl /= 1000.0;
    							this.ypl = this.tpi + this.haw + this.tps + this.hs - this.u1;
    						}
    						else
    						{
    							this.nr = (this.bs * this.hs * this.fcd + this.afs * this.fydar + this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi) / 2.0;
    							if (this.bs * this.hs * this.fcd + this.afs * this.fydar + this.bps * this.tps * this.fydps > this.nr)
    							{
    								this.clp = 1;
    								this.ctp = 1000.0;
    								this.u1 = (this.nr - this.afs * this.fydar - this.bs * this.hs * this.fcd) / (this.bps * this.fydps);
    								this.mpl = this.bs * this.hs * this.fcd * (this.hs / 2.0 + this.u1);
    								this.mpl += this.afs * this.fydar * (this.hs + this.u1 - this.rs);
    								this.mpl += this.bps * this.u1 * this.fydps * this.u1 / 2.0;
    								this.mpl += this.bps * (this.tps - this.u1) * this.fydps * (this.tps - this.u1) / 2.0;
    								this.mpl += this.haw * this.taw * this.fyda * (this.tps + this.haw / 2.0 - this.u1);
    								this.mpl += this.tpi * this.bpi * this.fydpi * (this.tps + this.haw + this.tpi / 2.0 - this.u1);
    								this.mpl /= 1000.0;
    								this.ypl = this.tpi + this.haw + this.tps - this.u1;
    							}
    							else if (this.bs * this.hs * this.fcd + this.afs * this.fydar + this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda > this.nr)
    							{
    								this.u2 = (this.nr - this.bs * this.hs * this.fcd - this.afs * this.fydar - this.bps * this.tps * this.fydps) / (this.fyda * this.taw);
    								this.u3 = this.haw - this.u2;
    								this.ua = this.u2 / this.haw;
    								this.clp = 0;
    								this.colorTextBox53 = "Red";
    								this.mpl = 0.0;
    								this.ctp = 396.0 * this.ue / (13.0 * this.ua - 1.0);
    								if (this.ua <= 0.5)
    								{
    									this.ctp = 36.0 * this.ue / this.ua;
    								}
    								if (this.ctp >= this.ctr)
    								{
    									this.clp = 1;
    									this.colorTextBox53 = "Green";
    								}
    								else
    								{
    									this.ctp = 456.0 * this.ue / (13.0 * this.ua - 1.0);
    									if (this.ua <= 0.5)
    									{
    										this.ctp = 41.5 * this.ue / this.ua;
    									}
    									if (this.ctp < this.ctr)
    									{
    										goto IL_38C4;
    									}
    									this.clp = 2;
    									this.colorTextBox53 = "Green";
    								}
    								this.mpl = this.bs * this.hs * this.fcd * (this.hs / 2.0 + this.tps + this.u2);
    								this.mpl += this.afs * this.fydar * (this.hs + this.tps + this.u2 - this.rs);
    								this.mpl += this.bps * this.tps * this.fydps * (this.tps / 2.0 + this.u2);
    								this.mpl += this.u2 * this.taw * this.fyda * this.u2 / 2.0;
    								this.mpl += this.u3 * this.taw * this.fyda * this.u3 / 2.0;
    								this.mpl += this.tpi * this.bpi * this.fydpi * (this.u3 + this.tpi / 2.0);
    								this.mpl /= 1000.0;
    								this.ypl = this.tpi + this.haw - this.u2;
    							}
    							else if (this.ctr > 38.0 * this.ue)
    							{
    								this.clp = -1;
    								this.mpl = 0.0;
    								this.colorTextBox53 = "Red";
    							}
    							else
    							{
    								this.clp = 2;
    								this.ctp = this.ctr;
    								if (this.ctr <= 33.0 * this.ue)
    								{
    									this.clp = 1;
    								}
    								this.u1 = (this.bs * this.hs * this.fcd + this.afs * this.fydar + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi + this.tps * this.bps * this.fydps) / 2.0 / (this.fydpi * this.bpi);
    								this.mpl = this.bpi * this.u1 * this.fydpi * this.u1 / 2.0;
    								this.mpl += this.bpi * (this.tpi - this.u1) * this.fydpi * (this.tpi - this.u1) / 2.0;
    								this.mpl += this.haw * this.taw * this.fyda * (this.haw / 2.0 + this.tpi - this.u1);
    								this.mpl += this.tps * this.bps * this.fydps * (this.tps / 2.0 + this.haw + this.tpi - this.u1);
    								this.mpl += this.afs * this.fydar * (this.tpi + this.haw + this.tps + this.hs - this.rs - this.u1);
    								this.mpl += this.bs * this.hs * this.fcd * (this.tpi + this.haw + this.tps + this.hs / 2.0 - this.u1);
    								this.ypl = this.u1;
    							}
    						}
    					}
    				}
    			}
    			else if (this.mtot < 0.0)
    			{
    				this.nr = (this.afs * this.fydar + this.bps * this.tps * this.fydps + this.haw * this.taw * this.fyda + this.bpi * this.tpi * this.fydpi) / 2.0;
    				if (this.bpi * this.tpi * this.fydpi > this.nr)
    				{
    					this.clp = 1;
    					this.ctp = 1000.0;
    					this.u1 = this.nr / (this.bpi * this.fydpi);
    					this.mpl = this.bpi * this.u1 * this.fydpi * this.u1 / 2.0;
    					this.mpl += this.bpi * (this.tpi - this.u1) * this.fydpi * (this.tpi - this.u1) / 2.0;
    					this.mpl += this.haw * this.taw * this.fyda * (this.haw / 2.0 + this.tpi - this.u1);
    					this.mpl += this.tps * this.bps * this.fydps * (this.tps / 2.0 + this.haw + this.tpi - this.u1);
    					this.mpl += this.afs * this.fydar * (this.tpi + this.haw + this.tps + this.hs - this.rs - this.u1);
    					this.mpl = -this.mpl / 1000.0;
    					this.ypl = this.u1;
    				}
    				else if (this.bpi * this.tpi * this.fydpi + this.haw * this.taw * this.fyda > this.nr)
    				{
    					this.colorTextBox53 = "Green";
    					this.u3 = (this.nr - this.bpi * this.tpi * this.fydpi) / (this.fyda * this.taw);
    					this.u2 = this.haw - this.u3;
    					this.ua = this.u3 / this.haw;
    					this.clp = 0;
    					this.colorTextBox53 = "Red";
    					this.mpl = 0.0;
    					this.ctp = 396.0 * this.ue / (13.0 * this.ua - 1.0);
    					if (this.ua <= 0.5)
    					{
    						this.ctp = 36.0 * this.ue / this.ua;
    					}
    					if (this.ctp >= this.ctr)
    					{
    						this.clp = 1;
    						this.colorTextBox53 = "Green";
    					}
    					else
    					{
    						this.ctp = 456.0 * this.ue / (13.0 * this.ua - 1.0);
    						if (this.ua <= 0.5)
    						{
    							this.ctp = 41.5 * this.ue / this.ua;
    						}
    						if (this.ctp < this.ctr)
    						{
    							goto IL_38C4;
    						}
    						this.clp = 2;
    						this.colorTextBox53 = "Green";
    					}
    					this.mpl += this.afs * this.fydar * (this.hs + this.tps + this.u2 - this.rs);
    					this.mpl += this.bps * this.tps * this.fydps * (this.tps / 2.0 + this.u2);
    					this.mpl += this.u2 * this.taw * this.fyda * this.u2 / 2.0;
    					this.mpl += this.u3 * this.taw * this.fyda * this.u3 / 2.0;
    					this.mpl += this.tpi * this.bpi * this.fydpi * (this.u3 + this.tpi / 2.0);
    					this.mpl = -this.mpl / 1000.0;
    					this.ypl = this.tpi + this.u3;
    				}
    				else if (this.bpi * this.tpi * this.fydpi + this.tps * this.fydps * this.bps + this.taw * this.haw * this.fyda > this.nr)
    				{
    					if (this.ctr > 38.0 * this.ue)
    					{
    						this.clp = -1;
    						this.mpl = 0.0;
    						this.colorTextBox53 = "Red";
    					}
    					else
    					{
    						this.clp = 2;
    						this.ctp = this.ctr;
    						if (this.ctr <= 33.0 * this.ue)
    						{
    							this.clp = 1;
    						}
    						this.u1 = (this.nr - this.afs * this.fydar) / (this.fydps * this.bps);
    						this.mpl = this.bpi * this.tpi * this.fydpi * (this.tpi / 2.0 + this.haw + this.tps - this.u1);
    						this.mpl += this.haw * this.taw * this.fyda * (this.haw / 2.0 + this.tps - this.u1);
    						this.mpl += (this.tps - this.u1) * (this.tps - this.u1) / 2.0 * this.bps * this.fydps;
    						this.mpl += this.u1 * this.bps * this.fydps * this.u1 / 2.0;
    						this.mpl += this.afs * this.fydar * (this.hs - this.rs + this.u1);
    						this.mpl = -this.mpl / 1000.0;
    						this.ypl = this.tpi + this.haw + this.tps - this.u1;
    					}
    				}
    				else if (this.ctr > 38.0 * this.ue)
    				{
    					this.clp = -1;
    					this.mpl = 0.0;
    					this.colorTextBox53 = "Red";
    				}
    				else
    				{
    					this.clp = 2;
    					this.ctp = this.ctr;
    					if (this.ctr <= 33.0 * this.ue)
    					{
    						this.clp = 1;
    					}
    					this.u1 = this.hs - this.rs;
    					this.mpl = this.bpi * this.tpi * this.fydpi * (this.tpi / 2.0 + this.haw + this.tps);
    					this.mpl += this.haw * this.taw * this.fyda * (this.haw / 2.0 + this.tps);
    					this.mpl += this.tps * this.tps / 2.0 * this.bps * this.fydps;
    					this.mpl += this.nr * this.u1;
    					this.mpl = -this.mpl / 1000.0;
    					this.ypl = this.tpi + this.haw + this.tps;
    				}
    			}
    			IL_38C4:
    			if (this.mpl == 0.0)
    			{
    				this.nibeta = 1.0;
    			}
    			else
    			{
    				this.u1 = this.haw * this.taw * this.fyda / Math.Sqrt(3.0) / 10.0;
    				if (this.ttot > 0.5 * this.u1 & this.iterp == 0)
    				{
    					this.fyda = this.fyda1 * (1.0 - Math.Pow(2.0 * this.ttot / this.u1 - 1.0, 2.0));
    					this.colorTextBox47 = "Red";
    					this.iterp = 1;
    					goto IL_212E;
    				}
    				this.colorTextBox13 = "Green";
    				this.nibeta = this.mtot / this.mpl;
    				if (this.nibeta >= 1.0)
    				{
    					this.colorTextBox13 = "Red";
    				}
    			}
    			this.outTextBox44 = this.yginf;
    			this.outTextBox40 = this.ainf;
    			this.outTextBox38 = this.jxinf;
    			this.outTextBox42 = this.ygninf;
    			this.outTextBox36 = this.aninf;
    			this.outTextBox39 = this.jxninf;
    			this.outTextBox43 = this.ygn0;
    			this.outTextBox37 = this.an0;
    			this.outTextBox41 = this.jxn0;
    			this.outTextBox2 = this.hs;
    			this.outTextBox9 = this.bs;
    			this.outTextBox18 = this.rs;
    			this.outTextBox24 = this.afs;
    			this.outTextBox8 = this.tps;
    			this.outTextBox7 = this.bps;
    			this.outTextBox4 = this.haw;
    			this.outTextBox1 = this.taw;
    			this.outTextBox3 = this.tpi;
    			this.outTextBox17 = this.bpi;
    			this.outTextBox5 = this.n0;
    			this.outTextBox6 = this.ninf;
    			this.outTextBox16 = this.fydar;
    			this.outTextBox32 = this.sninf;
    			this.outTextBox33 = this.stinf;
    			this.outTextBox34 = this.sminf;
    			this.outTextBox27 = this.snninf;
    			this.outTextBox28 = this.stninf;
    			this.outTextBox29 = this.smninf;
    			this.outTextBox11 = this.snn0;
    			this.outTextBox30 = this.stn0;
    			this.outTextBox31 = this.smn0;
    			this.outTextBox22 = this.sig1;
    			this.outTextBox35 = this.sig2;
    			this.outTextBox19 = this.sig3;
    			this.outTextBox14 = this.sigid3;
    			this.outTextBox23 = this.sig4;
    			this.outTextBox21 = this.sigid4;
    			this.outTextBox10 = this.tau4;
    			this.outTextBox12 = this.sig5;
    			this.outTextBox25 = this.sigid5;
    			this.outTextBox15 = this.sig6;
    			this.outTextBox26 = this.sigid6;
    			this.outTextBox20 = this.taub;
    			this.outTextBox57 = this.mtot;
    			this.outTextBox58 = this.ttot;
    			this.outTextBox13 = this.nibeta;
    			this.outTextBox59 = this.mpl;
    			this.outTextBox60 = this.yel;
    			this.outTextBox61 = this.ypl;
    			this.outTextBox45 = this.fcd;
    			this.outTextBox46 = this.fydps;
    			this.outTextBox47 = this.fyda1;
    			this.outTextBox48 = this.fydpi;
    			this.outTextBox49 = this.cte;
    			this.outTextBox50 = this.ctr;
    			this.outTextBox52 = this.ctp;
    			this.outTextBox51 = this.cle;
    			this.outTextBox53 = this.clp;
    			this.outTextBox62 = this.niter;
        }
    }
}
