<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>GPC.Checker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GPCGeometry" Version="2.0.0.3" />
    <PackageReference Include="GPCModel" Version="1.0.1.6" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GPCGeometry">
      <HintPath>..\..\gpc-geometry\GPCGeometry\bin\Debug\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
    <Reference Include="GPCModel">
      <HintPath>..\..\gpc-model\GPCModel\bin\Debug\netstandard2.0\GPCModel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
