<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>GPC.Checker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GPCGeometry" Version="2.0.1" />
    <PackageReference Include="GPCUtilities" Version="2.0.0.5" />
  </ItemGroup>

  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' Or '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Reference Include="GPCModel">
      <HintPath>..\..\GPCModel\GPCModel\bin\$(Configuration)\netstandard2.0\GPCModel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
