<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>GPC.Checker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GPCGeometry" Version="2.0.0.4" />
    <PackageReference Include="GPCUtilities" Version="2.0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GPCModel">
      <HintPath>..\..\gpc-model\GPCModel\bin\Debug\netstandard2.0\GPCModel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
