<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>GPC.Checker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GPCGeometry" Version="2.0.0.4" />
    <PackageReference Include="GPCModel" Version="1.0.2.4" />
    <PackageReference Include="GPCUtilities" Version="2.0.0.2" />
  </ItemGroup>

</Project>
